# Generated by Django 4.1.3 on 2022-12-13 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_contab'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtab',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
