# Generated by Django 4.1.3 on 2022-12-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_newtab_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='tab1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
