# Generated by Django 4.1.3 on 2023-02-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_tab1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tab1',
            new_name='admin',
        ),
        migrations.RenameModel(
            old_name='newtab',
            new_name='user',
        ),
    ]
