# Generated by Django 4.1.3 on 2023-02-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_rename_tab1_admin_rename_newtab_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='u_tab',
        ),
    ]
